/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginResetPasswordRouteImport } from './routes/login_.reset-password'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as CampaignsSlugRouteImport } from './routes/campaigns.$slug'
import { Route as CampaignsSlugIndexRouteImport } from './routes/campaigns.$slug.index'
import { Route as LoginCallbackProviderRouteImport } from './routes/login_.callback.$provider'
import { Route as CampaignsSlugJoinInviteCodeRouteImport } from './routes/campaigns_.$slug.join.$inviteCode'
import { Route as CampaignsSlugCharactersCharacterSlugRouteImport } from './routes/campaigns.$slug.characters.$characterSlug'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginResetPasswordRoute = LoginResetPasswordRouteImport.update({
  id: '/login_/reset-password',
  path: '/login/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugRoute = CampaignsSlugRouteImport.update({
  id: '/campaigns/$slug',
  path: '/campaigns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugIndexRoute = CampaignsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsSlugRoute,
} as any)
const LoginCallbackProviderRoute = LoginCallbackProviderRouteImport.update({
  id: '/login_/callback/$provider',
  path: '/login/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugJoinInviteCodeRoute =
  CampaignsSlugJoinInviteCodeRouteImport.update({
    id: '/campaigns_/$slug/join/$inviteCode',
    path: '/campaigns/$slug/join/$inviteCode',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsSlugCharactersCharacterSlugRoute =
  CampaignsSlugCharactersCharacterSlugRouteImport.update({
    id: '/characters/$characterSlug',
    path: '/characters/$characterSlug',
    getParentRoute: () => CampaignsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/campaigns/$slug': typeof CampaignsSlugRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/login/callback/$provider': typeof LoginCallbackProviderRoute
  '/campaigns/$slug/': typeof CampaignsSlugIndexRoute
  '/campaigns/$slug/characters/$characterSlug': typeof CampaignsSlugCharactersCharacterSlugRoute
  '/campaigns/$slug/join/$inviteCode': typeof CampaignsSlugJoinInviteCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/login/callback/$provider': typeof LoginCallbackProviderRoute
  '/campaigns/$slug': typeof CampaignsSlugIndexRoute
  '/campaigns/$slug/characters/$characterSlug': typeof CampaignsSlugCharactersCharacterSlugRoute
  '/campaigns/$slug/join/$inviteCode': typeof CampaignsSlugJoinInviteCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/campaigns/$slug': typeof CampaignsSlugRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/login_/reset-password': typeof LoginResetPasswordRoute
  '/login_/callback/$provider': typeof LoginCallbackProviderRoute
  '/campaigns/$slug/': typeof CampaignsSlugIndexRoute
  '/campaigns/$slug/characters/$characterSlug': typeof CampaignsSlugCharactersCharacterSlugRoute
  '/campaigns_/$slug/join/$inviteCode': typeof CampaignsSlugJoinInviteCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/campaigns/$slug'
    | '/campaigns/new'
    | '/login/reset-password'
    | '/login/callback/$provider'
    | '/campaigns/$slug/'
    | '/campaigns/$slug/characters/$characterSlug'
    | '/campaigns/$slug/join/$inviteCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/campaigns/new'
    | '/login/reset-password'
    | '/login/callback/$provider'
    | '/campaigns/$slug'
    | '/campaigns/$slug/characters/$characterSlug'
    | '/campaigns/$slug/join/$inviteCode'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/campaigns/$slug'
    | '/campaigns/new'
    | '/login_/reset-password'
    | '/login_/callback/$provider'
    | '/campaigns/$slug/'
    | '/campaigns/$slug/characters/$characterSlug'
    | '/campaigns_/$slug/join/$inviteCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OnboardingRoute: typeof OnboardingRoute
  CampaignsSlugRoute: typeof CampaignsSlugRouteWithChildren
  CampaignsNewRoute: typeof CampaignsNewRoute
  LoginResetPasswordRoute: typeof LoginResetPasswordRoute
  LoginCallbackProviderRoute: typeof LoginCallbackProviderRoute
  CampaignsSlugJoinInviteCodeRoute: typeof CampaignsSlugJoinInviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/reset-password': {
      id: '/login_/reset-password'
      path: '/login/reset-password'
      fullPath: '/login/reset-password'
      preLoaderRoute: typeof LoginResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug': {
      id: '/campaigns/$slug'
      path: '/campaigns/$slug'
      fullPath: '/campaigns/$slug'
      preLoaderRoute: typeof CampaignsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug/': {
      id: '/campaigns/$slug/'
      path: '/'
      fullPath: '/campaigns/$slug/'
      preLoaderRoute: typeof CampaignsSlugIndexRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/login_/callback/$provider': {
      id: '/login_/callback/$provider'
      path: '/login/callback/$provider'
      fullPath: '/login/callback/$provider'
      preLoaderRoute: typeof LoginCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns_/$slug/join/$inviteCode': {
      id: '/campaigns_/$slug/join/$inviteCode'
      path: '/campaigns/$slug/join/$inviteCode'
      fullPath: '/campaigns/$slug/join/$inviteCode'
      preLoaderRoute: typeof CampaignsSlugJoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug/characters/$characterSlug': {
      id: '/campaigns/$slug/characters/$characterSlug'
      path: '/characters/$characterSlug'
      fullPath: '/campaigns/$slug/characters/$characterSlug'
      preLoaderRoute: typeof CampaignsSlugCharactersCharacterSlugRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
  }
}

interface CampaignsSlugRouteChildren {
  CampaignsSlugIndexRoute: typeof CampaignsSlugIndexRoute
  CampaignsSlugCharactersCharacterSlugRoute: typeof CampaignsSlugCharactersCharacterSlugRoute
}

const CampaignsSlugRouteChildren: CampaignsSlugRouteChildren = {
  CampaignsSlugIndexRoute: CampaignsSlugIndexRoute,
  CampaignsSlugCharactersCharacterSlugRoute:
    CampaignsSlugCharactersCharacterSlugRoute,
}

const CampaignsSlugRouteWithChildren = CampaignsSlugRoute._addFileChildren(
  CampaignsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OnboardingRoute: OnboardingRoute,
  CampaignsSlugRoute: CampaignsSlugRouteWithChildren,
  CampaignsNewRoute: CampaignsNewRoute,
  LoginResetPasswordRoute: LoginResetPasswordRoute,
  LoginCallbackProviderRoute: LoginCallbackProviderRoute,
  CampaignsSlugJoinInviteCodeRoute: CampaignsSlugJoinInviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
