/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginResetPasswordRouteImport } from './routes/login_.reset-password'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as CampaignsSlugRouteImport } from './routes/campaigns.$slug'
import { Route as CampaignsSlugIndexRouteImport } from './routes/campaigns.$slug.index'
import { Route as LoginCallbackProviderRouteImport } from './routes/login_.callback.$provider'
import { Route as CampaignsSlugSettingsRouteImport } from './routes/campaigns.$slug.settings'
import { Route as CampaignsSlugItemsIndexRouteImport } from './routes/campaigns.$slug.items.index'
import { Route as CampaignsSlugChronicleIndexRouteImport } from './routes/campaigns.$slug.chronicle.index'
import { Route as CampaignsSlugCharactersIndexRouteImport } from './routes/campaigns.$slug.characters.index'
import { Route as CampaignsSlugInvitesInviteCodeRouteImport } from './routes/campaigns_.$slug.invites.$inviteCode'
import { Route as CampaignsSlugItemsItemSlugRouteImport } from './routes/campaigns.$slug.items.$itemSlug'
import { Route as CampaignsSlugChronicleNewRouteImport } from './routes/campaigns.$slug.chronicle.new'
import { Route as CampaignsSlugChronicleEntrySlugRouteImport } from './routes/campaigns.$slug.chronicle.$entrySlug'
import { Route as CampaignsSlugCharactersCharacterSlugRouteImport } from './routes/campaigns.$slug.characters.$characterSlug'
import { Route as CampaignsSlugChronicleEntrySlugEditRouteImport } from './routes/campaigns.$slug.chronicle.$entrySlug_.edit'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginResetPasswordRoute = LoginResetPasswordRouteImport.update({
  id: '/login_/reset-password',
  path: '/login/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugRoute = CampaignsSlugRouteImport.update({
  id: '/campaigns/$slug',
  path: '/campaigns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugIndexRoute = CampaignsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsSlugRoute,
} as any)
const LoginCallbackProviderRoute = LoginCallbackProviderRouteImport.update({
  id: '/login_/callback/$provider',
  path: '/login/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugSettingsRoute = CampaignsSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CampaignsSlugRoute,
} as any)
const CampaignsSlugItemsIndexRoute = CampaignsSlugItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => CampaignsSlugRoute,
} as any)
const CampaignsSlugChronicleIndexRoute =
  CampaignsSlugChronicleIndexRouteImport.update({
    id: '/chronicle/',
    path: '/chronicle/',
    getParentRoute: () => CampaignsSlugRoute,
  } as any)
const CampaignsSlugCharactersIndexRoute =
  CampaignsSlugCharactersIndexRouteImport.update({
    id: '/characters/',
    path: '/characters/',
    getParentRoute: () => CampaignsSlugRoute,
  } as any)
const CampaignsSlugInvitesInviteCodeRoute =
  CampaignsSlugInvitesInviteCodeRouteImport.update({
    id: '/campaigns_/$slug/invites/$inviteCode',
    path: '/campaigns/$slug/invites/$inviteCode',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsSlugItemsItemSlugRoute =
  CampaignsSlugItemsItemSlugRouteImport.update({
    id: '/items/$itemSlug',
    path: '/items/$itemSlug',
    getParentRoute: () => CampaignsSlugRoute,
  } as any)
const CampaignsSlugChronicleNewRoute =
  CampaignsSlugChronicleNewRouteImport.update({
    id: '/chronicle/new',
    path: '/chronicle/new',
    getParentRoute: () => CampaignsSlugRoute,
  } as any)
const CampaignsSlugChronicleEntrySlugRoute =
  CampaignsSlugChronicleEntrySlugRouteImport.update({
    id: '/chronicle/$entrySlug',
    path: '/chronicle/$entrySlug',
    getParentRoute: () => CampaignsSlugRoute,
  } as any)
const CampaignsSlugCharactersCharacterSlugRoute =
  CampaignsSlugCharactersCharacterSlugRouteImport.update({
    id: '/characters/$characterSlug',
    path: '/characters/$characterSlug',
    getParentRoute: () => CampaignsSlugRoute,
  } as any)
const CampaignsSlugChronicleEntrySlugEditRoute =
  CampaignsSlugChronicleEntrySlugEditRouteImport.update({
    id: '/chronicle/$entrySlug_/edit',
    path: '/chronicle/$entrySlug/edit',
    getParentRoute: () => CampaignsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/campaigns/$slug': typeof CampaignsSlugRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/campaigns/$slug/settings': typeof CampaignsSlugSettingsRoute
  '/login/callback/$provider': typeof LoginCallbackProviderRoute
  '/campaigns/$slug/': typeof CampaignsSlugIndexRoute
  '/campaigns/$slug/characters/$characterSlug': typeof CampaignsSlugCharactersCharacterSlugRoute
  '/campaigns/$slug/chronicle/$entrySlug': typeof CampaignsSlugChronicleEntrySlugRoute
  '/campaigns/$slug/chronicle/new': typeof CampaignsSlugChronicleNewRoute
  '/campaigns/$slug/items/$itemSlug': typeof CampaignsSlugItemsItemSlugRoute
  '/campaigns/$slug/invites/$inviteCode': typeof CampaignsSlugInvitesInviteCodeRoute
  '/campaigns/$slug/characters/': typeof CampaignsSlugCharactersIndexRoute
  '/campaigns/$slug/chronicle/': typeof CampaignsSlugChronicleIndexRoute
  '/campaigns/$slug/items/': typeof CampaignsSlugItemsIndexRoute
  '/campaigns/$slug/chronicle/$entrySlug/edit': typeof CampaignsSlugChronicleEntrySlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/campaigns/$slug/settings': typeof CampaignsSlugSettingsRoute
  '/login/callback/$provider': typeof LoginCallbackProviderRoute
  '/campaigns/$slug': typeof CampaignsSlugIndexRoute
  '/campaigns/$slug/characters/$characterSlug': typeof CampaignsSlugCharactersCharacterSlugRoute
  '/campaigns/$slug/chronicle/$entrySlug': typeof CampaignsSlugChronicleEntrySlugRoute
  '/campaigns/$slug/chronicle/new': typeof CampaignsSlugChronicleNewRoute
  '/campaigns/$slug/items/$itemSlug': typeof CampaignsSlugItemsItemSlugRoute
  '/campaigns/$slug/invites/$inviteCode': typeof CampaignsSlugInvitesInviteCodeRoute
  '/campaigns/$slug/characters': typeof CampaignsSlugCharactersIndexRoute
  '/campaigns/$slug/chronicle': typeof CampaignsSlugChronicleIndexRoute
  '/campaigns/$slug/items': typeof CampaignsSlugItemsIndexRoute
  '/campaigns/$slug/chronicle/$entrySlug/edit': typeof CampaignsSlugChronicleEntrySlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/campaigns/$slug': typeof CampaignsSlugRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/login_/reset-password': typeof LoginResetPasswordRoute
  '/campaigns/$slug/settings': typeof CampaignsSlugSettingsRoute
  '/login_/callback/$provider': typeof LoginCallbackProviderRoute
  '/campaigns/$slug/': typeof CampaignsSlugIndexRoute
  '/campaigns/$slug/characters/$characterSlug': typeof CampaignsSlugCharactersCharacterSlugRoute
  '/campaigns/$slug/chronicle/$entrySlug': typeof CampaignsSlugChronicleEntrySlugRoute
  '/campaigns/$slug/chronicle/new': typeof CampaignsSlugChronicleNewRoute
  '/campaigns/$slug/items/$itemSlug': typeof CampaignsSlugItemsItemSlugRoute
  '/campaigns_/$slug/invites/$inviteCode': typeof CampaignsSlugInvitesInviteCodeRoute
  '/campaigns/$slug/characters/': typeof CampaignsSlugCharactersIndexRoute
  '/campaigns/$slug/chronicle/': typeof CampaignsSlugChronicleIndexRoute
  '/campaigns/$slug/items/': typeof CampaignsSlugItemsIndexRoute
  '/campaigns/$slug/chronicle/$entrySlug_/edit': typeof CampaignsSlugChronicleEntrySlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/campaigns/$slug'
    | '/campaigns/new'
    | '/login/reset-password'
    | '/campaigns/$slug/settings'
    | '/login/callback/$provider'
    | '/campaigns/$slug/'
    | '/campaigns/$slug/characters/$characterSlug'
    | '/campaigns/$slug/chronicle/$entrySlug'
    | '/campaigns/$slug/chronicle/new'
    | '/campaigns/$slug/items/$itemSlug'
    | '/campaigns/$slug/invites/$inviteCode'
    | '/campaigns/$slug/characters/'
    | '/campaigns/$slug/chronicle/'
    | '/campaigns/$slug/items/'
    | '/campaigns/$slug/chronicle/$entrySlug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/campaigns/new'
    | '/login/reset-password'
    | '/campaigns/$slug/settings'
    | '/login/callback/$provider'
    | '/campaigns/$slug'
    | '/campaigns/$slug/characters/$characterSlug'
    | '/campaigns/$slug/chronicle/$entrySlug'
    | '/campaigns/$slug/chronicle/new'
    | '/campaigns/$slug/items/$itemSlug'
    | '/campaigns/$slug/invites/$inviteCode'
    | '/campaigns/$slug/characters'
    | '/campaigns/$slug/chronicle'
    | '/campaigns/$slug/items'
    | '/campaigns/$slug/chronicle/$entrySlug/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/campaigns/$slug'
    | '/campaigns/new'
    | '/login_/reset-password'
    | '/campaigns/$slug/settings'
    | '/login_/callback/$provider'
    | '/campaigns/$slug/'
    | '/campaigns/$slug/characters/$characterSlug'
    | '/campaigns/$slug/chronicle/$entrySlug'
    | '/campaigns/$slug/chronicle/new'
    | '/campaigns/$slug/items/$itemSlug'
    | '/campaigns_/$slug/invites/$inviteCode'
    | '/campaigns/$slug/characters/'
    | '/campaigns/$slug/chronicle/'
    | '/campaigns/$slug/items/'
    | '/campaigns/$slug/chronicle/$entrySlug_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OnboardingRoute: typeof OnboardingRoute
  CampaignsSlugRoute: typeof CampaignsSlugRouteWithChildren
  CampaignsNewRoute: typeof CampaignsNewRoute
  LoginResetPasswordRoute: typeof LoginResetPasswordRoute
  LoginCallbackProviderRoute: typeof LoginCallbackProviderRoute
  CampaignsSlugInvitesInviteCodeRoute: typeof CampaignsSlugInvitesInviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/reset-password': {
      id: '/login_/reset-password'
      path: '/login/reset-password'
      fullPath: '/login/reset-password'
      preLoaderRoute: typeof LoginResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug': {
      id: '/campaigns/$slug'
      path: '/campaigns/$slug'
      fullPath: '/campaigns/$slug'
      preLoaderRoute: typeof CampaignsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug/': {
      id: '/campaigns/$slug/'
      path: '/'
      fullPath: '/campaigns/$slug/'
      preLoaderRoute: typeof CampaignsSlugIndexRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/login_/callback/$provider': {
      id: '/login_/callback/$provider'
      path: '/login/callback/$provider'
      fullPath: '/login/callback/$provider'
      preLoaderRoute: typeof LoginCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug/settings': {
      id: '/campaigns/$slug/settings'
      path: '/settings'
      fullPath: '/campaigns/$slug/settings'
      preLoaderRoute: typeof CampaignsSlugSettingsRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns/$slug/items/': {
      id: '/campaigns/$slug/items/'
      path: '/items'
      fullPath: '/campaigns/$slug/items/'
      preLoaderRoute: typeof CampaignsSlugItemsIndexRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns/$slug/chronicle/': {
      id: '/campaigns/$slug/chronicle/'
      path: '/chronicle'
      fullPath: '/campaigns/$slug/chronicle/'
      preLoaderRoute: typeof CampaignsSlugChronicleIndexRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns/$slug/characters/': {
      id: '/campaigns/$slug/characters/'
      path: '/characters'
      fullPath: '/campaigns/$slug/characters/'
      preLoaderRoute: typeof CampaignsSlugCharactersIndexRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns_/$slug/invites/$inviteCode': {
      id: '/campaigns_/$slug/invites/$inviteCode'
      path: '/campaigns/$slug/invites/$inviteCode'
      fullPath: '/campaigns/$slug/invites/$inviteCode'
      preLoaderRoute: typeof CampaignsSlugInvitesInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug/items/$itemSlug': {
      id: '/campaigns/$slug/items/$itemSlug'
      path: '/items/$itemSlug'
      fullPath: '/campaigns/$slug/items/$itemSlug'
      preLoaderRoute: typeof CampaignsSlugItemsItemSlugRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns/$slug/chronicle/new': {
      id: '/campaigns/$slug/chronicle/new'
      path: '/chronicle/new'
      fullPath: '/campaigns/$slug/chronicle/new'
      preLoaderRoute: typeof CampaignsSlugChronicleNewRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns/$slug/chronicle/$entrySlug': {
      id: '/campaigns/$slug/chronicle/$entrySlug'
      path: '/chronicle/$entrySlug'
      fullPath: '/campaigns/$slug/chronicle/$entrySlug'
      preLoaderRoute: typeof CampaignsSlugChronicleEntrySlugRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns/$slug/characters/$characterSlug': {
      id: '/campaigns/$slug/characters/$characterSlug'
      path: '/characters/$characterSlug'
      fullPath: '/campaigns/$slug/characters/$characterSlug'
      preLoaderRoute: typeof CampaignsSlugCharactersCharacterSlugRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns/$slug/chronicle/$entrySlug_/edit': {
      id: '/campaigns/$slug/chronicle/$entrySlug_/edit'
      path: '/chronicle/$entrySlug/edit'
      fullPath: '/campaigns/$slug/chronicle/$entrySlug/edit'
      preLoaderRoute: typeof CampaignsSlugChronicleEntrySlugEditRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
  }
}

interface CampaignsSlugRouteChildren {
  CampaignsSlugSettingsRoute: typeof CampaignsSlugSettingsRoute
  CampaignsSlugIndexRoute: typeof CampaignsSlugIndexRoute
  CampaignsSlugCharactersCharacterSlugRoute: typeof CampaignsSlugCharactersCharacterSlugRoute
  CampaignsSlugChronicleEntrySlugRoute: typeof CampaignsSlugChronicleEntrySlugRoute
  CampaignsSlugChronicleNewRoute: typeof CampaignsSlugChronicleNewRoute
  CampaignsSlugItemsItemSlugRoute: typeof CampaignsSlugItemsItemSlugRoute
  CampaignsSlugCharactersIndexRoute: typeof CampaignsSlugCharactersIndexRoute
  CampaignsSlugChronicleIndexRoute: typeof CampaignsSlugChronicleIndexRoute
  CampaignsSlugItemsIndexRoute: typeof CampaignsSlugItemsIndexRoute
  CampaignsSlugChronicleEntrySlugEditRoute: typeof CampaignsSlugChronicleEntrySlugEditRoute
}

const CampaignsSlugRouteChildren: CampaignsSlugRouteChildren = {
  CampaignsSlugSettingsRoute: CampaignsSlugSettingsRoute,
  CampaignsSlugIndexRoute: CampaignsSlugIndexRoute,
  CampaignsSlugCharactersCharacterSlugRoute:
    CampaignsSlugCharactersCharacterSlugRoute,
  CampaignsSlugChronicleEntrySlugRoute: CampaignsSlugChronicleEntrySlugRoute,
  CampaignsSlugChronicleNewRoute: CampaignsSlugChronicleNewRoute,
  CampaignsSlugItemsItemSlugRoute: CampaignsSlugItemsItemSlugRoute,
  CampaignsSlugCharactersIndexRoute: CampaignsSlugCharactersIndexRoute,
  CampaignsSlugChronicleIndexRoute: CampaignsSlugChronicleIndexRoute,
  CampaignsSlugItemsIndexRoute: CampaignsSlugItemsIndexRoute,
  CampaignsSlugChronicleEntrySlugEditRoute:
    CampaignsSlugChronicleEntrySlugEditRoute,
}

const CampaignsSlugRouteWithChildren = CampaignsSlugRoute._addFileChildren(
  CampaignsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OnboardingRoute: OnboardingRoute,
  CampaignsSlugRoute: CampaignsSlugRouteWithChildren,
  CampaignsNewRoute: CampaignsNewRoute,
  LoginResetPasswordRoute: LoginResetPasswordRoute,
  LoginCallbackProviderRoute: LoginCallbackProviderRoute,
  CampaignsSlugInvitesInviteCodeRoute: CampaignsSlugInvitesInviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
