"""campaigns

Revision ID: 0004
Revises: 0003
Create Date: 2026-06-13 20:55:31.303597

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("slug_label", sa.String(), nullable=False),
        sa.Column("slug_id", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug_id", name="uq_campaigns_slug_id"),
    )
    op.create_index("ix_campaigns_owner_id_created_at", "campaigns", ["owner_id", "created_at"], unique=False)
    op.create_index(op.f("ix_campaigns_slug_id"), "campaigns", ["slug_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_campaigns_slug_id"), table_name="campaigns")
    op.drop_index("ix_campaigns_owner_id_created_at", table_name="campaigns")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
