"""membership

Revision ID: 0005
Revises: 0004
Create Date: 2026-06-14 00:25:41.350069

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign_members",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("campaign_id", "user_id"),
    )
    op.create_index("ix_campaign_members_user_id", "campaign_members", ["user_id"], unique=False)
    op.add_column("campaigns", sa.Column("invite_code", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "invite_code")
    op.drop_index("ix_campaign_members_user_id", table_name="campaign_members")
    op.drop_table("campaign_members")
    # ### end Alembic commands ###
