"""character and item image key

Revision ID: 0010
Revises: 0009
Create Date: 2026-07-06 22:11:49.138147

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("image_key", sa.String(), nullable=True))
    op.drop_index(op.f("ix_chronicle_entries_campaign_id"), table_name="chronicle_entries")
    op.create_index(
        "ix_chronicle_entries_campaign_occurred_at",
        "chronicle_entries",
        ["campaign_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.add_column("items", sa.Column("image_key", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "image_key")
    op.drop_index("ix_chronicle_entries_campaign_occurred_at", table_name="chronicle_entries")
    op.create_index(op.f("ix_chronicle_entries_campaign_id"), "chronicle_entries", ["campaign_id"], unique=False)
    op.drop_column("characters", "image_key")
    # ### end Alembic commands ###
