"""restricted entities

Revision ID: 0011
Revises: 0010
Create Date: 2026-07-10 22:05:04.588371

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("restricted", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column(
        "chronicle_entries", sa.Column("restricted", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column("items", sa.Column("restricted", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "restricted")
    op.drop_column("chronicle_entries", "restricted")
    op.drop_column("characters", "restricted")
    # ### end Alembic commands ###
