"""add tags to lore entities

Revision ID: 0013
Revises: 0012
Create Date: 2026-07-13 22:02:39.814960

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters", sa.Column("tags", sa.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False)
    )
    op.add_column(
        "chronicle_entries", sa.Column("tags", sa.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False)
    )
    op.add_column("items", sa.Column("tags", sa.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False))
    op.add_column("locations", sa.Column("tags", sa.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "tags")
    op.drop_column("items", "tags")
    op.drop_column("chronicle_entries", "tags")
    op.drop_column("characters", "tags")
    # ### end Alembic commands ###
